// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package pkt2axil_regmap_pkg;

    localparam PKT2AXIL_REGMAP_DATA_WIDTH = 32;
    localparam PKT2AXIL_REGMAP_MIN_ADDR_WIDTH = 32;
    localparam PKT2AXIL_REGMAP_SIZE = 'hc0;

    typedef struct {
        logic [31:0] next;
    } test_r_0__data__in_t;

    typedef struct {
        test_r_0__data__in_t data;
    } test_r_0__in_t;

    typedef struct {
        logic [31:0] next;
    } test_r_1__data__in_t;

    typedef struct {
        test_r_1__data__in_t data;
    } test_r_1__in_t;

    typedef struct {
        logic [31:0] next;
    } test_r_2__data__in_t;

    typedef struct {
        test_r_2__data__in_t data;
    } test_r_2__in_t;

    typedef struct {
        logic [31:0] next;
    } test_r_3__data__in_t;

    typedef struct {
        test_r_3__data__in_t data;
    } test_r_3__in_t;

    typedef struct {
        logic [31:0] next;
    } test_r_4__data__in_t;

    typedef struct {
        test_r_4__data__in_t data;
    } test_r_4__in_t;

    typedef struct {
        logic [31:0] next;
    } test_r_5__data__in_t;

    typedef struct {
        test_r_5__data__in_t data;
    } test_r_5__in_t;

    typedef struct {
        logic [31:0] next;
    } test_r_6__data__in_t;

    typedef struct {
        test_r_6__data__in_t data;
    } test_r_6__in_t;

    typedef struct {
        logic [31:0] next;
    } test_r_7__data__in_t;

    typedef struct {
        test_r_7__data__in_t data;
    } test_r_7__in_t;

    typedef struct {
        logic [31:0] next;
    } test_r_8__data__in_t;

    typedef struct {
        test_r_8__data__in_t data;
    } test_r_8__in_t;

    typedef struct {
        logic [31:0] next;
    } test_r_9__data__in_t;

    typedef struct {
        test_r_9__data__in_t data;
    } test_r_9__in_t;

    typedef struct {
        logic [31:0] next;
    } test_r_10__data__in_t;

    typedef struct {
        test_r_10__data__in_t data;
    } test_r_10__in_t;

    typedef struct {
        logic [31:0] next;
    } test_r_11__data__in_t;

    typedef struct {
        test_r_11__data__in_t data;
    } test_r_11__in_t;

    typedef struct {
        logic [31:0] next;
    } test_r_12__data__in_t;

    typedef struct {
        test_r_12__data__in_t data;
    } test_r_12__in_t;

    typedef struct {
        logic [31:0] next;
    } test_r_13__data__in_t;

    typedef struct {
        test_r_13__data__in_t data;
    } test_r_13__in_t;

    typedef struct {
        logic [31:0] next;
    } test_r_14__data__in_t;

    typedef struct {
        test_r_14__data__in_t data;
    } test_r_14__in_t;

    typedef struct {
        logic [31:0] next;
    } test_r_15__data__in_t;

    typedef struct {
        test_r_15__data__in_t data;
    } test_r_15__in_t;

    typedef struct {
        test_r_0__in_t test_r_0;
        test_r_1__in_t test_r_1;
        test_r_2__in_t test_r_2;
        test_r_3__in_t test_r_3;
        test_r_4__in_t test_r_4;
        test_r_5__in_t test_r_5;
        test_r_6__in_t test_r_6;
        test_r_7__in_t test_r_7;
        test_r_8__in_t test_r_8;
        test_r_9__in_t test_r_9;
        test_r_10__in_t test_r_10;
        test_r_11__in_t test_r_11;
        test_r_12__in_t test_r_12;
        test_r_13__in_t test_r_13;
        test_r_14__in_t test_r_14;
        test_r_15__in_t test_r_15;
    } pkt2axil_regmap__in_t;

    typedef struct {
        logic [31:0] value;
    } test_rw_0__data__out_t;

    typedef struct {
        test_rw_0__data__out_t data;
    } test_rw_0__out_t;

    typedef struct {
        logic [31:0] value;
    } test_rw_1__data__out_t;

    typedef struct {
        test_rw_1__data__out_t data;
    } test_rw_1__out_t;

    typedef struct {
        logic [31:0] value;
    } test_rw_2__data__out_t;

    typedef struct {
        test_rw_2__data__out_t data;
    } test_rw_2__out_t;

    typedef struct {
        logic [31:0] value;
    } test_rw_3__data__out_t;

    typedef struct {
        test_rw_3__data__out_t data;
    } test_rw_3__out_t;

    typedef struct {
        logic [31:0] value;
    } test_rw_4__data__out_t;

    typedef struct {
        test_rw_4__data__out_t data;
    } test_rw_4__out_t;

    typedef struct {
        logic [31:0] value;
    } test_rw_5__data__out_t;

    typedef struct {
        test_rw_5__data__out_t data;
    } test_rw_5__out_t;

    typedef struct {
        logic [31:0] value;
    } test_rw_6__data__out_t;

    typedef struct {
        test_rw_6__data__out_t data;
    } test_rw_6__out_t;

    typedef struct {
        logic [31:0] value;
    } test_rw_7__data__out_t;

    typedef struct {
        test_rw_7__data__out_t data;
    } test_rw_7__out_t;

    typedef struct {
        logic [31:0] value;
    } test_rw_8__data__out_t;

    typedef struct {
        test_rw_8__data__out_t data;
    } test_rw_8__out_t;

    typedef struct {
        logic [31:0] value;
    } test_rw_9__data__out_t;

    typedef struct {
        test_rw_9__data__out_t data;
    } test_rw_9__out_t;

    typedef struct {
        logic [31:0] value;
    } test_rw_10__data__out_t;

    typedef struct {
        test_rw_10__data__out_t data;
    } test_rw_10__out_t;

    typedef struct {
        logic [31:0] value;
    } test_rw_11__data__out_t;

    typedef struct {
        test_rw_11__data__out_t data;
    } test_rw_11__out_t;

    typedef struct {
        logic [31:0] value;
    } test_rw_12__data__out_t;

    typedef struct {
        test_rw_12__data__out_t data;
    } test_rw_12__out_t;

    typedef struct {
        logic [31:0] value;
    } test_rw_13__data__out_t;

    typedef struct {
        test_rw_13__data__out_t data;
    } test_rw_13__out_t;

    typedef struct {
        logic [31:0] value;
    } test_rw_14__data__out_t;

    typedef struct {
        test_rw_14__data__out_t data;
    } test_rw_14__out_t;

    typedef struct {
        logic [31:0] value;
    } test_rw_15__data__out_t;

    typedef struct {
        test_rw_15__data__out_t data;
    } test_rw_15__out_t;

    typedef struct {
        logic [31:0] value;
    } test_w_0__data__out_t;

    typedef struct {
        test_w_0__data__out_t data;
    } test_w_0__out_t;

    typedef struct {
        logic [31:0] value;
    } test_w_1__data__out_t;

    typedef struct {
        test_w_1__data__out_t data;
    } test_w_1__out_t;

    typedef struct {
        logic [31:0] value;
    } test_w_2__data__out_t;

    typedef struct {
        test_w_2__data__out_t data;
    } test_w_2__out_t;

    typedef struct {
        logic [31:0] value;
    } test_w_3__data__out_t;

    typedef struct {
        test_w_3__data__out_t data;
    } test_w_3__out_t;

    typedef struct {
        logic [31:0] value;
    } test_w_4__data__out_t;

    typedef struct {
        test_w_4__data__out_t data;
    } test_w_4__out_t;

    typedef struct {
        logic [31:0] value;
    } test_w_5__data__out_t;

    typedef struct {
        test_w_5__data__out_t data;
    } test_w_5__out_t;

    typedef struct {
        logic [31:0] value;
    } test_w_6__data__out_t;

    typedef struct {
        test_w_6__data__out_t data;
    } test_w_6__out_t;

    typedef struct {
        logic [31:0] value;
    } test_w_7__data__out_t;

    typedef struct {
        test_w_7__data__out_t data;
    } test_w_7__out_t;

    typedef struct {
        logic [31:0] value;
    } test_w_8__data__out_t;

    typedef struct {
        test_w_8__data__out_t data;
    } test_w_8__out_t;

    typedef struct {
        logic [31:0] value;
    } test_w_9__data__out_t;

    typedef struct {
        test_w_9__data__out_t data;
    } test_w_9__out_t;

    typedef struct {
        logic [31:0] value;
    } test_w_10__data__out_t;

    typedef struct {
        test_w_10__data__out_t data;
    } test_w_10__out_t;

    typedef struct {
        logic [31:0] value;
    } test_w_11__data__out_t;

    typedef struct {
        test_w_11__data__out_t data;
    } test_w_11__out_t;

    typedef struct {
        logic [31:0] value;
    } test_w_12__data__out_t;

    typedef struct {
        test_w_12__data__out_t data;
    } test_w_12__out_t;

    typedef struct {
        logic [31:0] value;
    } test_w_13__data__out_t;

    typedef struct {
        test_w_13__data__out_t data;
    } test_w_13__out_t;

    typedef struct {
        logic [31:0] value;
    } test_w_14__data__out_t;

    typedef struct {
        test_w_14__data__out_t data;
    } test_w_14__out_t;

    typedef struct {
        logic [31:0] value;
    } test_w_15__data__out_t;

    typedef struct {
        test_w_15__data__out_t data;
    } test_w_15__out_t;

    typedef struct {
        test_rw_0__out_t test_rw_0;
        test_rw_1__out_t test_rw_1;
        test_rw_2__out_t test_rw_2;
        test_rw_3__out_t test_rw_3;
        test_rw_4__out_t test_rw_4;
        test_rw_5__out_t test_rw_5;
        test_rw_6__out_t test_rw_6;
        test_rw_7__out_t test_rw_7;
        test_rw_8__out_t test_rw_8;
        test_rw_9__out_t test_rw_9;
        test_rw_10__out_t test_rw_10;
        test_rw_11__out_t test_rw_11;
        test_rw_12__out_t test_rw_12;
        test_rw_13__out_t test_rw_13;
        test_rw_14__out_t test_rw_14;
        test_rw_15__out_t test_rw_15;
        test_w_0__out_t test_w_0;
        test_w_1__out_t test_w_1;
        test_w_2__out_t test_w_2;
        test_w_3__out_t test_w_3;
        test_w_4__out_t test_w_4;
        test_w_5__out_t test_w_5;
        test_w_6__out_t test_w_6;
        test_w_7__out_t test_w_7;
        test_w_8__out_t test_w_8;
        test_w_9__out_t test_w_9;
        test_w_10__out_t test_w_10;
        test_w_11__out_t test_w_11;
        test_w_12__out_t test_w_12;
        test_w_13__out_t test_w_13;
        test_w_14__out_t test_w_14;
        test_w_15__out_t test_w_15;
    } pkt2axil_regmap__out_t;
endpackage
