// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module pkt2axil_regmap (
        input wire clk,
        input wire rst_n,

        output logic s_axil_awready,
        input wire s_axil_awvalid,
        input wire [31:0] s_axil_awaddr,
        input wire [2:0] s_axil_awprot,
        output logic s_axil_wready,
        input wire s_axil_wvalid,
        input wire [31:0] s_axil_wdata,
        input wire [3:0]s_axil_wstrb,
        input wire s_axil_bready,
        output logic s_axil_bvalid,
        output logic [1:0] s_axil_bresp,
        output logic s_axil_arready,
        input wire s_axil_arvalid,
        input wire [31:0] s_axil_araddr,
        input wire [2:0] s_axil_arprot,
        input wire s_axil_rready,
        output logic s_axil_rvalid,
        output logic [31:0] s_axil_rdata,
        output logic [1:0] s_axil_rresp,

        input pkt2axil_regmap_pkg::pkt2axil_regmap__in_t hwif_in,
        output pkt2axil_regmap_pkg::pkt2axil_regmap__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [31:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Max Outstanding Transactions: 2
    logic [1:0] axil_n_in_flight;
    logic axil_prev_was_rd;
    logic axil_arvalid;
    logic [31:0] axil_araddr;
    logic axil_ar_accept;
    logic axil_awvalid;
    logic [31:0] axil_awaddr;
    logic axil_wvalid;
    logic [31:0] axil_wdata;
    logic [3:0] axil_wstrb;
    logic axil_aw_accept;
    logic axil_resp_acked;

    // Transaction request acceptance
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            axil_prev_was_rd <= '0;
            axil_arvalid <= '0;
            axil_araddr <= '0;
            axil_awvalid <= '0;
            axil_awaddr <= '0;
            axil_wvalid <= '0;
            axil_wdata <= '0;
            axil_wstrb <= '0;
            axil_n_in_flight <= '0;
        end else begin
            // AR* acceptance register
            if(axil_ar_accept) begin
                axil_prev_was_rd <= '1;
                axil_arvalid <= '0;
            end
            if(s_axil_arvalid && s_axil_arready) begin
                axil_arvalid <= '1;
                axil_araddr <= s_axil_araddr;
            end

            // AW* & W* acceptance registers
            if(axil_aw_accept) begin
                axil_prev_was_rd <= '0;
                axil_awvalid <= '0;
                axil_wvalid <= '0;
            end
            if(s_axil_awvalid && s_axil_awready) begin
                axil_awvalid <= '1;
                axil_awaddr <= s_axil_awaddr;
            end
            if(s_axil_wvalid && s_axil_wready) begin
                axil_wvalid <= '1;
                axil_wdata <= s_axil_wdata;
                axil_wstrb <= s_axil_wstrb;
            end

            // Keep track of in-flight transactions
            if((axil_ar_accept || axil_aw_accept) && !axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight + 1'b1;
            end else if(!(axil_ar_accept || axil_aw_accept) && axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight - 1'b1;
            end
        end
    end

    always_comb begin
        s_axil_arready = (!axil_arvalid || axil_ar_accept);
        s_axil_awready = (!axil_awvalid || axil_aw_accept);
        s_axil_wready = (!axil_wvalid || axil_aw_accept);
    end

    // Request dispatch
    always_comb begin
        cpuif_wr_data = axil_wdata;
        for(int i=0; i<4; i++) begin
            cpuif_wr_biten[i*8 +: 8] = {8{axil_wstrb[i]}};
        end
        cpuif_req = '0;
        cpuif_req_is_wr = '0;
        cpuif_addr = '0;
        axil_ar_accept = '0;
        axil_aw_accept = '0;

        if(axil_n_in_flight < 2'd2) begin
            // Can safely issue more transactions without overwhelming response buffer
            if(axil_arvalid && !axil_prev_was_rd) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = {axil_araddr[31:2], 2'b0};
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end else if(axil_awvalid && axil_wvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '1;
                cpuif_addr = {axil_awaddr[31:2], 2'b0};
                if(!cpuif_req_stall_wr) axil_aw_accept = '1;
            end else if(axil_arvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = {axil_araddr[31:2], 2'b0};
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end
        end
    end


    // AXI4-Lite Response Logic
    struct {
        logic is_wr;
        logic err;
        logic [31:0] rdata;
    } axil_resp_buffer[2];

    logic [1:0] axil_resp_wptr;
    logic [1:0] axil_resp_rptr;

    always_ff @(posedge clk) begin
        if(~rst_n) begin
            for(int i=0; i<2; i++) begin
                axil_resp_buffer[i].is_wr <= '0;
                axil_resp_buffer[i].err <= '0;
                axil_resp_buffer[i].rdata <= '0;
            end
            axil_resp_wptr <= '0;
            axil_resp_rptr <= '0;
            bresp_handshake_done <= '0;
        end else begin
            // Запоминаем факт завершения B-channel handshake для явного сброса bvalid
            bresp_handshake_done <= s_axil_bvalid & s_axil_bready;
            // Store responses in buffer until AXI response channel accepts them
            if(cpuif_rd_ack || cpuif_wr_ack) begin
                if(cpuif_rd_ack) begin
                    axil_resp_buffer[axil_resp_wptr[0:0]].is_wr <= '0;
                    axil_resp_buffer[axil_resp_wptr[0:0]].err <= cpuif_rd_err;
                    axil_resp_buffer[axil_resp_wptr[0:0]].rdata <= cpuif_rd_data;

                end else if(cpuif_wr_ack) begin
                    axil_resp_buffer[axil_resp_wptr[0:0]].is_wr <= '1;
                    axil_resp_buffer[axil_resp_wptr[0:0]].err <= cpuif_wr_err;
                end
                axil_resp_wptr <= axil_resp_wptr + 1'b1;
            end

            // Advance read pointer when acknowledged
            if(axil_resp_acked) begin
                axil_resp_rptr <= axil_resp_rptr + 1'b1;
            end
        end
    end

    always_comb begin
        axil_resp_acked = '0;
        s_axil_bvalid = '0;
        s_axil_rvalid = '0;
        if(axil_resp_rptr != axil_resp_wptr) begin
            if(axil_resp_buffer[axil_resp_rptr[0:0]].is_wr) begin
                s_axil_bvalid = '1;
                if(s_axil_bready) axil_resp_acked = '1;
            end else begin
                s_axil_rvalid = '1;
                if(s_axil_rready) axil_resp_acked = '1;
            end
        end

        s_axil_rdata = axil_resp_buffer[axil_resp_rptr[0:0]].rdata;
        if(axil_resp_buffer[axil_resp_rptr[0:0]].err) begin
            s_axil_bresp = 2'b10;
            s_axil_rresp = 2'b10;
        end else begin
            s_axil_bresp = 2'b00;
            s_axil_rresp = 2'b00;
        end
    end

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic test_rw_0;
        logic test_rw_1;
        logic test_rw_2;
        logic test_rw_3;
        logic test_rw_4;
        logic test_rw_5;
        logic test_rw_6;
        logic test_rw_7;
        logic test_rw_8;
        logic test_rw_9;
        logic test_rw_10;
        logic test_rw_11;
        logic test_rw_12;
        logic test_rw_13;
        logic test_rw_14;
        logic test_rw_15;
        logic test_w_0;
        logic test_w_1;
        logic test_w_2;
        logic test_w_3;
        logic test_w_4;
        logic test_w_5;
        logic test_w_6;
        logic test_w_7;
        logic test_w_8;
        logic test_w_9;
        logic test_w_10;
        logic test_w_11;
        logic test_w_12;
        logic test_w_13;
        logic test_w_14;
        logic test_w_15;
        logic test_r_0;
        logic test_r_1;
        logic test_r_2;
        logic test_r_3;
        logic test_r_4;
        logic test_r_5;
        logic test_r_6;
        logic test_r_7;
        logic test_r_8;
        logic test_r_9;
        logic test_r_10;
        logic test_r_11;
        logic test_r_12;
        logic test_r_13;
        logic test_r_14;
        logic test_r_15;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_invalid_rw;
        is_valid_addr = '1; // No error checking on valid address access
        is_invalid_rw = '0;
        decoded_reg_strb.test_rw_0 = cpuif_req_masked & (cpuif_addr == 32'h0);
        decoded_reg_strb.test_rw_1 = cpuif_req_masked & (cpuif_addr == 32'h4);
        decoded_reg_strb.test_rw_2 = cpuif_req_masked & (cpuif_addr == 32'h8);
        decoded_reg_strb.test_rw_3 = cpuif_req_masked & (cpuif_addr == 32'hc);
        decoded_reg_strb.test_rw_4 = cpuif_req_masked & (cpuif_addr == 32'h10);
        decoded_reg_strb.test_rw_5 = cpuif_req_masked & (cpuif_addr == 32'h14);
        decoded_reg_strb.test_rw_6 = cpuif_req_masked & (cpuif_addr == 32'h18);
        decoded_reg_strb.test_rw_7 = cpuif_req_masked & (cpuif_addr == 32'h1c);
        decoded_reg_strb.test_rw_8 = cpuif_req_masked & (cpuif_addr == 32'h20);
        decoded_reg_strb.test_rw_9 = cpuif_req_masked & (cpuif_addr == 32'h24);
        decoded_reg_strb.test_rw_10 = cpuif_req_masked & (cpuif_addr == 32'h28);
        decoded_reg_strb.test_rw_11 = cpuif_req_masked & (cpuif_addr == 32'h2c);
        decoded_reg_strb.test_rw_12 = cpuif_req_masked & (cpuif_addr == 32'h30);
        decoded_reg_strb.test_rw_13 = cpuif_req_masked & (cpuif_addr == 32'h34);
        decoded_reg_strb.test_rw_14 = cpuif_req_masked & (cpuif_addr == 32'h38);
        decoded_reg_strb.test_rw_15 = cpuif_req_masked & (cpuif_addr == 32'h3c);
        decoded_reg_strb.test_w_0 = cpuif_req_masked & (cpuif_addr == 32'h40) & cpuif_req_is_wr;
        decoded_reg_strb.test_w_1 = cpuif_req_masked & (cpuif_addr == 32'h44) & cpuif_req_is_wr;
        decoded_reg_strb.test_w_2 = cpuif_req_masked & (cpuif_addr == 32'h48) & cpuif_req_is_wr;
        decoded_reg_strb.test_w_3 = cpuif_req_masked & (cpuif_addr == 32'h4c) & cpuif_req_is_wr;
        decoded_reg_strb.test_w_4 = cpuif_req_masked & (cpuif_addr == 32'h50) & cpuif_req_is_wr;
        decoded_reg_strb.test_w_5 = cpuif_req_masked & (cpuif_addr == 32'h54) & cpuif_req_is_wr;
        decoded_reg_strb.test_w_6 = cpuif_req_masked & (cpuif_addr == 32'h58) & cpuif_req_is_wr;
        decoded_reg_strb.test_w_7 = cpuif_req_masked & (cpuif_addr == 32'h5c) & cpuif_req_is_wr;
        decoded_reg_strb.test_w_8 = cpuif_req_masked & (cpuif_addr == 32'h60) & cpuif_req_is_wr;
        decoded_reg_strb.test_w_9 = cpuif_req_masked & (cpuif_addr == 32'h64) & cpuif_req_is_wr;
        decoded_reg_strb.test_w_10 = cpuif_req_masked & (cpuif_addr == 32'h68) & cpuif_req_is_wr;
        decoded_reg_strb.test_w_11 = cpuif_req_masked & (cpuif_addr == 32'h6c) & cpuif_req_is_wr;
        decoded_reg_strb.test_w_12 = cpuif_req_masked & (cpuif_addr == 32'h70) & cpuif_req_is_wr;
        decoded_reg_strb.test_w_13 = cpuif_req_masked & (cpuif_addr == 32'h74) & cpuif_req_is_wr;
        decoded_reg_strb.test_w_14 = cpuif_req_masked & (cpuif_addr == 32'h78) & cpuif_req_is_wr;
        decoded_reg_strb.test_w_15 = cpuif_req_masked & (cpuif_addr == 32'h7c) & cpuif_req_is_wr;
        decoded_reg_strb.test_r_0 = cpuif_req_masked & (cpuif_addr == 32'h80) & !cpuif_req_is_wr;
        decoded_reg_strb.test_r_1 = cpuif_req_masked & (cpuif_addr == 32'h84) & !cpuif_req_is_wr;
        decoded_reg_strb.test_r_2 = cpuif_req_masked & (cpuif_addr == 32'h88) & !cpuif_req_is_wr;
        decoded_reg_strb.test_r_3 = cpuif_req_masked & (cpuif_addr == 32'h8c) & !cpuif_req_is_wr;
        decoded_reg_strb.test_r_4 = cpuif_req_masked & (cpuif_addr == 32'h90) & !cpuif_req_is_wr;
        decoded_reg_strb.test_r_5 = cpuif_req_masked & (cpuif_addr == 32'h94) & !cpuif_req_is_wr;
        decoded_reg_strb.test_r_6 = cpuif_req_masked & (cpuif_addr == 32'h98) & !cpuif_req_is_wr;
        decoded_reg_strb.test_r_7 = cpuif_req_masked & (cpuif_addr == 32'h9c) & !cpuif_req_is_wr;
        decoded_reg_strb.test_r_8 = cpuif_req_masked & (cpuif_addr == 32'ha0) & !cpuif_req_is_wr;
        decoded_reg_strb.test_r_9 = cpuif_req_masked & (cpuif_addr == 32'ha4) & !cpuif_req_is_wr;
        decoded_reg_strb.test_r_10 = cpuif_req_masked & (cpuif_addr == 32'ha8) & !cpuif_req_is_wr;
        decoded_reg_strb.test_r_11 = cpuif_req_masked & (cpuif_addr == 32'hac) & !cpuif_req_is_wr;
        decoded_reg_strb.test_r_12 = cpuif_req_masked & (cpuif_addr == 32'hb0) & !cpuif_req_is_wr;
        decoded_reg_strb.test_r_13 = cpuif_req_masked & (cpuif_addr == 32'hb4) & !cpuif_req_is_wr;
        decoded_reg_strb.test_r_14 = cpuif_req_masked & (cpuif_addr == 32'hb8) & !cpuif_req_is_wr;
        decoded_reg_strb.test_r_15 = cpuif_req_masked & (cpuif_addr == 32'hbc) & !cpuif_req_is_wr;
        decoded_err = (~is_valid_addr | is_invalid_rw) & decoded_req;
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_rw_0;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_rw_1;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_rw_2;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_rw_3;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_rw_4;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_rw_5;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_rw_6;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_rw_7;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_rw_8;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_rw_9;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_rw_10;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_rw_11;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_rw_12;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_rw_13;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_rw_14;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_rw_15;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_w_0;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_w_1;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_w_2;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_w_3;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_w_4;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_w_5;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_w_6;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_w_7;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_w_8;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_w_9;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_w_10;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_w_11;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_w_12;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_w_13;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_w_14;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } data;
        } test_w_15;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_rw_0;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_rw_1;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_rw_2;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_rw_3;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_rw_4;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_rw_5;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_rw_6;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_rw_7;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_rw_8;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_rw_9;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_rw_10;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_rw_11;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_rw_12;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_rw_13;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_rw_14;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_rw_15;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_w_0;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_w_1;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_w_2;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_w_3;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_w_4;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_w_5;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_w_6;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_w_7;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_w_8;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_w_9;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_w_10;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_w_11;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_w_12;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_w_13;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_w_14;
        struct {
            struct {
                logic [31:0] value;
            } data;
        } test_w_15;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: pkt2axil_regmap.test_rw_0.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_rw_0.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_rw_0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_rw_0.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_rw_0.data.next = next_c;
        field_combo.test_rw_0.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_rw_0.data.value <= 32'h0;
        end else begin
            if(field_combo.test_rw_0.data.load_next) begin
                field_storage.test_rw_0.data.value <= field_combo.test_rw_0.data.next;
            end
        end
    end
    assign hwif_out.test_rw_0.data.value = field_storage.test_rw_0.data.value;
    // Field: pkt2axil_regmap.test_rw_1.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_rw_1.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_rw_1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_rw_1.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_rw_1.data.next = next_c;
        field_combo.test_rw_1.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_rw_1.data.value <= 32'h0;
        end else begin
            if(field_combo.test_rw_1.data.load_next) begin
                field_storage.test_rw_1.data.value <= field_combo.test_rw_1.data.next;
            end
        end
    end
    assign hwif_out.test_rw_1.data.value = field_storage.test_rw_1.data.value;
    // Field: pkt2axil_regmap.test_rw_2.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_rw_2.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_rw_2 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_rw_2.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_rw_2.data.next = next_c;
        field_combo.test_rw_2.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_rw_2.data.value <= 32'h0;
        end else begin
            if(field_combo.test_rw_2.data.load_next) begin
                field_storage.test_rw_2.data.value <= field_combo.test_rw_2.data.next;
            end
        end
    end
    assign hwif_out.test_rw_2.data.value = field_storage.test_rw_2.data.value;
    // Field: pkt2axil_regmap.test_rw_3.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_rw_3.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_rw_3 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_rw_3.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_rw_3.data.next = next_c;
        field_combo.test_rw_3.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_rw_3.data.value <= 32'h0;
        end else begin
            if(field_combo.test_rw_3.data.load_next) begin
                field_storage.test_rw_3.data.value <= field_combo.test_rw_3.data.next;
            end
        end
    end
    assign hwif_out.test_rw_3.data.value = field_storage.test_rw_3.data.value;
    // Field: pkt2axil_regmap.test_rw_4.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_rw_4.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_rw_4 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_rw_4.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_rw_4.data.next = next_c;
        field_combo.test_rw_4.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_rw_4.data.value <= 32'h0;
        end else begin
            if(field_combo.test_rw_4.data.load_next) begin
                field_storage.test_rw_4.data.value <= field_combo.test_rw_4.data.next;
            end
        end
    end
    assign hwif_out.test_rw_4.data.value = field_storage.test_rw_4.data.value;
    // Field: pkt2axil_regmap.test_rw_5.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_rw_5.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_rw_5 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_rw_5.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_rw_5.data.next = next_c;
        field_combo.test_rw_5.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_rw_5.data.value <= 32'h0;
        end else begin
            if(field_combo.test_rw_5.data.load_next) begin
                field_storage.test_rw_5.data.value <= field_combo.test_rw_5.data.next;
            end
        end
    end
    assign hwif_out.test_rw_5.data.value = field_storage.test_rw_5.data.value;
    // Field: pkt2axil_regmap.test_rw_6.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_rw_6.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_rw_6 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_rw_6.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_rw_6.data.next = next_c;
        field_combo.test_rw_6.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_rw_6.data.value <= 32'h0;
        end else begin
            if(field_combo.test_rw_6.data.load_next) begin
                field_storage.test_rw_6.data.value <= field_combo.test_rw_6.data.next;
            end
        end
    end
    assign hwif_out.test_rw_6.data.value = field_storage.test_rw_6.data.value;
    // Field: pkt2axil_regmap.test_rw_7.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_rw_7.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_rw_7 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_rw_7.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_rw_7.data.next = next_c;
        field_combo.test_rw_7.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_rw_7.data.value <= 32'h0;
        end else begin
            if(field_combo.test_rw_7.data.load_next) begin
                field_storage.test_rw_7.data.value <= field_combo.test_rw_7.data.next;
            end
        end
    end
    assign hwif_out.test_rw_7.data.value = field_storage.test_rw_7.data.value;
    // Field: pkt2axil_regmap.test_rw_8.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_rw_8.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_rw_8 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_rw_8.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_rw_8.data.next = next_c;
        field_combo.test_rw_8.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_rw_8.data.value <= 32'h0;
        end else begin
            if(field_combo.test_rw_8.data.load_next) begin
                field_storage.test_rw_8.data.value <= field_combo.test_rw_8.data.next;
            end
        end
    end
    assign hwif_out.test_rw_8.data.value = field_storage.test_rw_8.data.value;
    // Field: pkt2axil_regmap.test_rw_9.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_rw_9.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_rw_9 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_rw_9.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_rw_9.data.next = next_c;
        field_combo.test_rw_9.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_rw_9.data.value <= 32'h0;
        end else begin
            if(field_combo.test_rw_9.data.load_next) begin
                field_storage.test_rw_9.data.value <= field_combo.test_rw_9.data.next;
            end
        end
    end
    assign hwif_out.test_rw_9.data.value = field_storage.test_rw_9.data.value;
    // Field: pkt2axil_regmap.test_rw_10.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_rw_10.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_rw_10 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_rw_10.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_rw_10.data.next = next_c;
        field_combo.test_rw_10.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_rw_10.data.value <= 32'h0;
        end else begin
            if(field_combo.test_rw_10.data.load_next) begin
                field_storage.test_rw_10.data.value <= field_combo.test_rw_10.data.next;
            end
        end
    end
    assign hwif_out.test_rw_10.data.value = field_storage.test_rw_10.data.value;
    // Field: pkt2axil_regmap.test_rw_11.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_rw_11.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_rw_11 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_rw_11.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_rw_11.data.next = next_c;
        field_combo.test_rw_11.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_rw_11.data.value <= 32'h0;
        end else begin
            if(field_combo.test_rw_11.data.load_next) begin
                field_storage.test_rw_11.data.value <= field_combo.test_rw_11.data.next;
            end
        end
    end
    assign hwif_out.test_rw_11.data.value = field_storage.test_rw_11.data.value;
    // Field: pkt2axil_regmap.test_rw_12.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_rw_12.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_rw_12 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_rw_12.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_rw_12.data.next = next_c;
        field_combo.test_rw_12.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_rw_12.data.value <= 32'h0;
        end else begin
            if(field_combo.test_rw_12.data.load_next) begin
                field_storage.test_rw_12.data.value <= field_combo.test_rw_12.data.next;
            end
        end
    end
    assign hwif_out.test_rw_12.data.value = field_storage.test_rw_12.data.value;
    // Field: pkt2axil_regmap.test_rw_13.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_rw_13.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_rw_13 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_rw_13.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_rw_13.data.next = next_c;
        field_combo.test_rw_13.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_rw_13.data.value <= 32'h0;
        end else begin
            if(field_combo.test_rw_13.data.load_next) begin
                field_storage.test_rw_13.data.value <= field_combo.test_rw_13.data.next;
            end
        end
    end
    assign hwif_out.test_rw_13.data.value = field_storage.test_rw_13.data.value;
    // Field: pkt2axil_regmap.test_rw_14.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_rw_14.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_rw_14 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_rw_14.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_rw_14.data.next = next_c;
        field_combo.test_rw_14.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_rw_14.data.value <= 32'h0;
        end else begin
            if(field_combo.test_rw_14.data.load_next) begin
                field_storage.test_rw_14.data.value <= field_combo.test_rw_14.data.next;
            end
        end
    end
    assign hwif_out.test_rw_14.data.value = field_storage.test_rw_14.data.value;
    // Field: pkt2axil_regmap.test_rw_15.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_rw_15.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_rw_15 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_rw_15.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_rw_15.data.next = next_c;
        field_combo.test_rw_15.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_rw_15.data.value <= 32'h0;
        end else begin
            if(field_combo.test_rw_15.data.load_next) begin
                field_storage.test_rw_15.data.value <= field_combo.test_rw_15.data.next;
            end
        end
    end
    assign hwif_out.test_rw_15.data.value = field_storage.test_rw_15.data.value;
    // Field: pkt2axil_regmap.test_w_0.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_w_0.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_w_0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_w_0.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_w_0.data.next = next_c;
        field_combo.test_w_0.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_w_0.data.value <= 32'h0;
        end else begin
            if(field_combo.test_w_0.data.load_next) begin
                field_storage.test_w_0.data.value <= field_combo.test_w_0.data.next;
            end
        end
    end
    assign hwif_out.test_w_0.data.value = field_storage.test_w_0.data.value;
    // Field: pkt2axil_regmap.test_w_1.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_w_1.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_w_1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_w_1.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_w_1.data.next = next_c;
        field_combo.test_w_1.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_w_1.data.value <= 32'h0;
        end else begin
            if(field_combo.test_w_1.data.load_next) begin
                field_storage.test_w_1.data.value <= field_combo.test_w_1.data.next;
            end
        end
    end
    assign hwif_out.test_w_1.data.value = field_storage.test_w_1.data.value;
    // Field: pkt2axil_regmap.test_w_2.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_w_2.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_w_2 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_w_2.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_w_2.data.next = next_c;
        field_combo.test_w_2.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_w_2.data.value <= 32'h0;
        end else begin
            if(field_combo.test_w_2.data.load_next) begin
                field_storage.test_w_2.data.value <= field_combo.test_w_2.data.next;
            end
        end
    end
    assign hwif_out.test_w_2.data.value = field_storage.test_w_2.data.value;
    // Field: pkt2axil_regmap.test_w_3.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_w_3.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_w_3 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_w_3.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_w_3.data.next = next_c;
        field_combo.test_w_3.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_w_3.data.value <= 32'h0;
        end else begin
            if(field_combo.test_w_3.data.load_next) begin
                field_storage.test_w_3.data.value <= field_combo.test_w_3.data.next;
            end
        end
    end
    assign hwif_out.test_w_3.data.value = field_storage.test_w_3.data.value;
    // Field: pkt2axil_regmap.test_w_4.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_w_4.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_w_4 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_w_4.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_w_4.data.next = next_c;
        field_combo.test_w_4.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_w_4.data.value <= 32'h0;
        end else begin
            if(field_combo.test_w_4.data.load_next) begin
                field_storage.test_w_4.data.value <= field_combo.test_w_4.data.next;
            end
        end
    end
    assign hwif_out.test_w_4.data.value = field_storage.test_w_4.data.value;
    // Field: pkt2axil_regmap.test_w_5.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_w_5.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_w_5 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_w_5.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_w_5.data.next = next_c;
        field_combo.test_w_5.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_w_5.data.value <= 32'h0;
        end else begin
            if(field_combo.test_w_5.data.load_next) begin
                field_storage.test_w_5.data.value <= field_combo.test_w_5.data.next;
            end
        end
    end
    assign hwif_out.test_w_5.data.value = field_storage.test_w_5.data.value;
    // Field: pkt2axil_regmap.test_w_6.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_w_6.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_w_6 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_w_6.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_w_6.data.next = next_c;
        field_combo.test_w_6.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_w_6.data.value <= 32'h0;
        end else begin
            if(field_combo.test_w_6.data.load_next) begin
                field_storage.test_w_6.data.value <= field_combo.test_w_6.data.next;
            end
        end
    end
    assign hwif_out.test_w_6.data.value = field_storage.test_w_6.data.value;
    // Field: pkt2axil_regmap.test_w_7.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_w_7.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_w_7 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_w_7.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_w_7.data.next = next_c;
        field_combo.test_w_7.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_w_7.data.value <= 32'h0;
        end else begin
            if(field_combo.test_w_7.data.load_next) begin
                field_storage.test_w_7.data.value <= field_combo.test_w_7.data.next;
            end
        end
    end
    assign hwif_out.test_w_7.data.value = field_storage.test_w_7.data.value;
    // Field: pkt2axil_regmap.test_w_8.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_w_8.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_w_8 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_w_8.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_w_8.data.next = next_c;
        field_combo.test_w_8.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_w_8.data.value <= 32'h0;
        end else begin
            if(field_combo.test_w_8.data.load_next) begin
                field_storage.test_w_8.data.value <= field_combo.test_w_8.data.next;
            end
        end
    end
    assign hwif_out.test_w_8.data.value = field_storage.test_w_8.data.value;
    // Field: pkt2axil_regmap.test_w_9.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_w_9.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_w_9 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_w_9.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_w_9.data.next = next_c;
        field_combo.test_w_9.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_w_9.data.value <= 32'h0;
        end else begin
            if(field_combo.test_w_9.data.load_next) begin
                field_storage.test_w_9.data.value <= field_combo.test_w_9.data.next;
            end
        end
    end
    assign hwif_out.test_w_9.data.value = field_storage.test_w_9.data.value;
    // Field: pkt2axil_regmap.test_w_10.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_w_10.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_w_10 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_w_10.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_w_10.data.next = next_c;
        field_combo.test_w_10.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_w_10.data.value <= 32'h0;
        end else begin
            if(field_combo.test_w_10.data.load_next) begin
                field_storage.test_w_10.data.value <= field_combo.test_w_10.data.next;
            end
        end
    end
    assign hwif_out.test_w_10.data.value = field_storage.test_w_10.data.value;
    // Field: pkt2axil_regmap.test_w_11.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_w_11.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_w_11 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_w_11.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_w_11.data.next = next_c;
        field_combo.test_w_11.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_w_11.data.value <= 32'h0;
        end else begin
            if(field_combo.test_w_11.data.load_next) begin
                field_storage.test_w_11.data.value <= field_combo.test_w_11.data.next;
            end
        end
    end
    assign hwif_out.test_w_11.data.value = field_storage.test_w_11.data.value;
    // Field: pkt2axil_regmap.test_w_12.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_w_12.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_w_12 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_w_12.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_w_12.data.next = next_c;
        field_combo.test_w_12.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_w_12.data.value <= 32'h0;
        end else begin
            if(field_combo.test_w_12.data.load_next) begin
                field_storage.test_w_12.data.value <= field_combo.test_w_12.data.next;
            end
        end
    end
    assign hwif_out.test_w_12.data.value = field_storage.test_w_12.data.value;
    // Field: pkt2axil_regmap.test_w_13.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_w_13.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_w_13 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_w_13.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_w_13.data.next = next_c;
        field_combo.test_w_13.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_w_13.data.value <= 32'h0;
        end else begin
            if(field_combo.test_w_13.data.load_next) begin
                field_storage.test_w_13.data.value <= field_combo.test_w_13.data.next;
            end
        end
    end
    assign hwif_out.test_w_13.data.value = field_storage.test_w_13.data.value;
    // Field: pkt2axil_regmap.test_w_14.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_w_14.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_w_14 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_w_14.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_w_14.data.next = next_c;
        field_combo.test_w_14.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_w_14.data.value <= 32'h0;
        end else begin
            if(field_combo.test_w_14.data.load_next) begin
                field_storage.test_w_14.data.value <= field_combo.test_w_14.data.next;
            end
        end
    end
    assign hwif_out.test_w_14.data.value = field_storage.test_w_14.data.value;
    // Field: pkt2axil_regmap.test_w_15.data
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.test_w_15.data.value;
        load_next_c = '0;
        if(decoded_reg_strb.test_w_15 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.test_w_15.data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.test_w_15.data.next = next_c;
        field_combo.test_w_15.data.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.test_w_15.data.value <= 32'h0;
        end else begin
            if(field_combo.test_w_15.data.load_next) begin
                field_storage.test_w_15.data.value <= field_combo.test_w_15.data.next;
            end
        end
    end
    assign hwif_out.test_w_15.data.value = field_storage.test_w_15.data.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[32];
    assign readback_array[0][31:0] = (decoded_reg_strb.test_rw_0 && !decoded_req_is_wr) ? field_storage.test_rw_0.data.value : '0;
    assign readback_array[1][31:0] = (decoded_reg_strb.test_rw_1 && !decoded_req_is_wr) ? field_storage.test_rw_1.data.value : '0;
    assign readback_array[2][31:0] = (decoded_reg_strb.test_rw_2 && !decoded_req_is_wr) ? field_storage.test_rw_2.data.value : '0;
    assign readback_array[3][31:0] = (decoded_reg_strb.test_rw_3 && !decoded_req_is_wr) ? field_storage.test_rw_3.data.value : '0;
    assign readback_array[4][31:0] = (decoded_reg_strb.test_rw_4 && !decoded_req_is_wr) ? field_storage.test_rw_4.data.value : '0;
    assign readback_array[5][31:0] = (decoded_reg_strb.test_rw_5 && !decoded_req_is_wr) ? field_storage.test_rw_5.data.value : '0;
    assign readback_array[6][31:0] = (decoded_reg_strb.test_rw_6 && !decoded_req_is_wr) ? field_storage.test_rw_6.data.value : '0;
    assign readback_array[7][31:0] = (decoded_reg_strb.test_rw_7 && !decoded_req_is_wr) ? field_storage.test_rw_7.data.value : '0;
    assign readback_array[8][31:0] = (decoded_reg_strb.test_rw_8 && !decoded_req_is_wr) ? field_storage.test_rw_8.data.value : '0;
    assign readback_array[9][31:0] = (decoded_reg_strb.test_rw_9 && !decoded_req_is_wr) ? field_storage.test_rw_9.data.value : '0;
    assign readback_array[10][31:0] = (decoded_reg_strb.test_rw_10 && !decoded_req_is_wr) ? field_storage.test_rw_10.data.value : '0;
    assign readback_array[11][31:0] = (decoded_reg_strb.test_rw_11 && !decoded_req_is_wr) ? field_storage.test_rw_11.data.value : '0;
    assign readback_array[12][31:0] = (decoded_reg_strb.test_rw_12 && !decoded_req_is_wr) ? field_storage.test_rw_12.data.value : '0;
    assign readback_array[13][31:0] = (decoded_reg_strb.test_rw_13 && !decoded_req_is_wr) ? field_storage.test_rw_13.data.value : '0;
    assign readback_array[14][31:0] = (decoded_reg_strb.test_rw_14 && !decoded_req_is_wr) ? field_storage.test_rw_14.data.value : '0;
    assign readback_array[15][31:0] = (decoded_reg_strb.test_rw_15 && !decoded_req_is_wr) ? field_storage.test_rw_15.data.value : '0;
    assign readback_array[16][31:0] = (decoded_reg_strb.test_r_0 && !decoded_req_is_wr) ? hwif_in.test_r_0.data.next : '0;
    assign readback_array[17][31:0] = (decoded_reg_strb.test_r_1 && !decoded_req_is_wr) ? hwif_in.test_r_1.data.next : '0;
    assign readback_array[18][31:0] = (decoded_reg_strb.test_r_2 && !decoded_req_is_wr) ? hwif_in.test_r_2.data.next : '0;
    assign readback_array[19][31:0] = (decoded_reg_strb.test_r_3 && !decoded_req_is_wr) ? hwif_in.test_r_3.data.next : '0;
    assign readback_array[20][31:0] = (decoded_reg_strb.test_r_4 && !decoded_req_is_wr) ? hwif_in.test_r_4.data.next : '0;
    assign readback_array[21][31:0] = (decoded_reg_strb.test_r_5 && !decoded_req_is_wr) ? hwif_in.test_r_5.data.next : '0;
    assign readback_array[22][31:0] = (decoded_reg_strb.test_r_6 && !decoded_req_is_wr) ? hwif_in.test_r_6.data.next : '0;
    assign readback_array[23][31:0] = (decoded_reg_strb.test_r_7 && !decoded_req_is_wr) ? hwif_in.test_r_7.data.next : '0;
    assign readback_array[24][31:0] = (decoded_reg_strb.test_r_8 && !decoded_req_is_wr) ? hwif_in.test_r_8.data.next : '0;
    assign readback_array[25][31:0] = (decoded_reg_strb.test_r_9 && !decoded_req_is_wr) ? hwif_in.test_r_9.data.next : '0;
    assign readback_array[26][31:0] = (decoded_reg_strb.test_r_10 && !decoded_req_is_wr) ? hwif_in.test_r_10.data.next : '0;
    assign readback_array[27][31:0] = (decoded_reg_strb.test_r_11 && !decoded_req_is_wr) ? hwif_in.test_r_11.data.next : '0;
    assign readback_array[28][31:0] = (decoded_reg_strb.test_r_12 && !decoded_req_is_wr) ? hwif_in.test_r_12.data.next : '0;
    assign readback_array[29][31:0] = (decoded_reg_strb.test_r_13 && !decoded_req_is_wr) ? hwif_in.test_r_13.data.next : '0;
    assign readback_array[30][31:0] = (decoded_reg_strb.test_r_14 && !decoded_req_is_wr) ? hwif_in.test_r_14.data.next : '0;
    assign readback_array[31][31:0] = (decoded_reg_strb.test_r_15 && !decoded_req_is_wr) ? hwif_in.test_r_15.data.next : '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<32; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
