TOPLEVEL_LANG = verilog

# По умолчанию используем Verilator, так как Icarus Verilog не поддерживает
# unpacked structs и некоторые конструкции SystemVerilog, используемые в reg_vmm
# Для использования Icarus Verilog: make SIM=icarus (может не работать из-за ограничений)
SIM ?= icarus
WAVES ?= 1

COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

DUT      = pkt2axil_top_tb
TOPLEVEL = $(DUT)
MODULE   = pkt2axil_test

# Пути к исходным файлам
VSRC_DIR = ../rtl
VSRC_DIR_TEST = ../tests
RDL_DIR = ../RDL/reg_vmm/rtl

# Основные файлы модуля
VSRC_SV = $(VSRC_DIR)/pkt2axil_top.sv \
          $(VSRC_DIR)/pkt2axil_cutter.sv \
          $(VSRC_DIR)/pkt2axil_binder.sv \
          $(VSRC_DIR)/pkt2axil_axis_fifo.sv \
          $(VSRC_DIR_TEST)/pkt2axil_top_tb.sv

# Файлы регистрового блока
RDL_SV = $(RDL_DIR)/reg_vmm_pkg.sv \
         $(RDL_DIR)/reg_vmm.sv

# Проверяем существование файлов
ifneq (,$(wildcard $(VSRC_DIR)/pkt2axil_top.sv))
    VERILOG_SOURCES += $(VSRC_DIR)/pkt2axil_top.sv
    $(info Using SystemVerilog source: $(VSRC_DIR)/pkt2axil_top.sv)
else
    $(error No source file found: $(VSRC_DIR)/pkt2axil_top.sv)
endif

# Используем оригинальные модули (streaming operator заменен на явную перестановку байтов)
ifneq (,$(wildcard $(VSRC_DIR)/pkt2axil_cutter.sv))
    VERILOG_SOURCES += $(VSRC_DIR)/pkt2axil_cutter.sv
    $(info Using SystemVerilog source: $(VSRC_DIR)/pkt2axil_cutter.sv)
else
    $(error No source file found: $(VSRC_DIR)/pkt2axil_cutter.sv)
endif

ifneq (,$(wildcard $(VSRC_DIR)/pkt2axil_binder.sv))
    VERILOG_SOURCES += $(VSRC_DIR)/pkt2axil_binder.sv
    $(info Using SystemVerilog source: $(VSRC_DIR)/pkt2axil_binder.sv)
else
    $(error No source file found: $(VSRC_DIR)/pkt2axil_binder.sv)
endif

ifneq (,$(wildcard $(VSRC_DIR)/pkt2axil_axis_fifo.sv))
    VERILOG_SOURCES += $(VSRC_DIR)/pkt2axil_axis_fifo.sv
    $(info Using SystemVerilog source: $(VSRC_DIR)/pkt2axil_axis_fifo.sv)
else
    $(error No source file found: $(VSRC_DIR)/pkt2axil_axis_fifo.sv)
endif

ifneq (,$(wildcard $(VSRC_DIR_TEST)/pkt2axil_top_tb.sv))
    VERILOG_SOURCES += $(VSRC_DIR_TEST)/pkt2axil_top_tb.sv
    $(info Using SystemVerilog source: $(VSRC_DIR_TEST)/pkt2axil_top_tb.sv)
else
    $(error No source file found: $(VSRC_DIR_TEST)/pkt2axil_top_tb.sv)
endif

# Путь к test_regmap
TEST_REGMAP_DIR = ../test_regmap/hw

# Используем regs_pkg.sv для всех симуляторов
ifneq (,$(wildcard $(TEST_REGMAP_DIR)/regs_pkg.sv))
    VERILOG_SOURCES += $(TEST_REGMAP_DIR)/regs_pkg.sv
    $(info Using SystemVerilog source: $(TEST_REGMAP_DIR)/regs_pkg.sv)
else
    $(error No source file found: $(TEST_REGMAP_DIR)/regs_pkg.sv)
endif

# Используем regs.v для всех симуляторов
ifneq (,$(wildcard $(TEST_REGMAP_DIR)/regs.v))
    VERILOG_SOURCES += $(TEST_REGMAP_DIR)/regs.v
    $(info Using Verilog source: $(TEST_REGMAP_DIR)/regs.v)
else
    $(error No source file found: $(TEST_REGMAP_DIR)/regs.v)
endif

# SystemVerilog support
# Для Icarus Verilog используем 2012, для Verilator - sv
ifeq ($(SIM), icarus)
	COMPILE_ARGS += -g2012
else ifeq ($(SIM), verilator)
	COMPILE_ARGS += -sv
endif

# module parameters
export PARAM_TDATA_WIDTH = 64
export PARAM_TKEEP_WIDTH = 8
export PARAM_TUSER_WIDTH = 8

ifeq ($(SIM), icarus)
	PLUSARGS += -fst
	
	# Определяем макрос для Icarus Verilog
	COMPILE_ARGS += -DICARUS_VERILOG

	COMPILE_ARGS += $(foreach v,$(filter PARAM_%,$(.VARIABLES)),-P $(TOPLEVEL).$(subst PARAM_,,$(v))=$($(v)))

	ifeq ($(WAVES), 1)
		VERILOG_SOURCES += iverilog_dump.v
		COMPILE_ARGS += -s iverilog_dump
	endif
else ifeq ($(SIM), verilator)
	COMPILE_ARGS += -Wno-SELRANGE -Wno-WIDTH
	COMPILE_ARGS += --build
	COMPILE_ARGS += -Wall
	COMPILE_ARGS += -sv

	COMPILE_ARGS += $(foreach v,$(filter PARAM_%,$(.VARIABLES)),-G$(subst PARAM_,,$(v))=$($(v)))

	ifeq ($(WAVES), 1)
		COMPILE_ARGS += --trace-fst
	endif
endif

include $(shell cocotb-config --makefiles)/Makefile.sim

iverilog_dump.v:
	echo 'module iverilog_dump();' > $@
	echo 'initial begin' >> $@
	echo '    $$dumpfile("$(TOPLEVEL).fst");' >> $@
	echo '    $$dumpvars(0, $(TOPLEVEL));' >> $@
	echo 'end' >> $@
	echo 'endmodule' >> $@

clean::
	@rm -rf iverilog_dump.v
	@rm -rf dump.fst $(TOPLEVEL).fst

# Additional test targets
test_write_read: MODULE = pkt2axil_test
test_write_read: TESTCASE = test_write_read
test_write_read: sim

.PHONY: test_write_read

